spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gym-finder
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  private-key: ${JWT_PRIVATE_KEY}
file:
  file-upload:
    path: ${FILE_UPLOAD_PATH}