name: Auto merge master into feature branches

on:
  push:
    branches:
      - master
    # Trigger on push to master branch

jobs:
  merge-into-feature-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name 'GitHub Actions'~
          git config --global user.email 'actions@github.com'

      - name: Get list of feature branches
        run: |
          # Get all branches that are not master (or any other branches you want to exclude)
          feature_branches=$(git branch -r | grep 'origin/features' | sed 's/origin\///')
          echo "Feature branches: $feature_branches"

      - name: Merge master into feature branches
        run: |
          # Loop through each feature branch and merge master into it
          for branch in $feature_branches; do
            echo "Merging master into $branch"
            git checkout $branch
            git pull origin $branch
            git merge origin/master --no-edit
            git push origin $branch
          done
